### ISSUE TITLE
Crash on 1.12.2 at startup, singleplayer not server

### ISSUE THREAD

**Issue by InuYasha86000** [kappa-maintainer/IndustrialWires-Classic#1]
I went to boot up my modpack with your version of IW, replacing this version (IndustrialWires-1.7-39) and the game failed to start at mod initializition phase
[crash-2023-06-25_21.55.16-client.txt](https://github.com/kappa-maintainer/IndustrialWires-Classic/files/11863865/crash-2023-06-25_21.55.16-client.txt)

**Comment by InuYasha86000** [comment]
to help, IndustrialWires-1.8-38 works. i'm not sure what the difference is between that one and yours but that might help.

**Comment by kappa-maintainer** [comment]
Sorry for late reply, my inbox must have flooded with junk mail in Jun
This mod is intended to be installed with IC2C, please use the [reengineered](https://www.curseforge.com/minecraft/mc-mods/industrial-wires-reengineered) version or [plus](https://www.curseforge.com/minecraft/mc-mods/industrial-wires-plus) version instead
